{
	// Cost of rematerializating x is 1
	let x := 0xff
	// First reference in loop to be rematerialized
	for {} lt(x, 0x100) {}
	{
		// Second reference in loop to be rematerialized
		let y := add(x, 1)
		let z := mul(x, 1)
		let a := div(x, 2)
		let b := mod(x, 3)
		let c := sdiv(x, 4)
	}
}
// ====
// step: rematerialiser
// ----
// {
//     let x := 0xff
//     for { } lt(x, 0x100) { }
//     {
//         let y := add(x, 1)
//         let z := mul(x, 1)
//         let a := div(x, 2)
//         let b := mod(x, 3)
//         let c := sdiv(x, 4)
//     }
// }
